# Every alarm notifies on ALARM and again on OK, so an email thread reads "broke ... recovered".
# Missing data (e.g. overnight, when the environment is torn down) counts as healthy.

# ---------- Users: what the load balancer sees ----------

# 5xx generated by the ALB itself, e.g. 503 "no healthy targets" or 502 from a dead frontend
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name          = "${var.name}-alb-5xx"
  alarm_description   = "ALB is returning 5xx itself: no healthy frontend targets or the frontend is unreachable"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  dimensions          = { LoadBalancer = local.alb }
  statistic           = "Sum"
  period              = 60
  evaluation_periods  = 3
  datapoints_to_alarm = 2
  threshold           = 5
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

# 5xx returned by the app (nginx passes the backend's 503 "Database unavailable" through)
resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  alarm_name          = "${var.name}-app-5xx"
  alarm_description   = "The application is returning 5xx responses (backend errors surface here through nginx)"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  dimensions          = { LoadBalancer = local.alb }
  statistic           = "Sum"
  period              = 60
  evaluation_periods  = 3
  datapoints_to_alarm = 2
  threshold           = 5
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

resource "aws_cloudwatch_metric_alarm" "frontend_unhealthy" {
  alarm_name          = "${var.name}-frontend-unhealthy-targets"
  alarm_description   = "At least one frontend task is failing the ALB health check"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "UnHealthyHostCount"
  dimensions          = { LoadBalancer = local.alb, TargetGroup = local.frontend_tg }
  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 2
  threshold           = 1
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

resource "aws_cloudwatch_metric_alarm" "slow_responses" {
  alarm_name          = "${var.name}-slow-responses"
  alarm_description   = "p95 response time above 1 second"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "TargetResponseTime"
  dimensions          = { LoadBalancer = local.alb }
  extended_statistic  = "p95"
  period              = 300
  evaluation_periods  = 2
  threshold           = 1
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

# ---------- ECS: per service ----------

# Container Insights metrics. Fires when ECS can't keep the desired number of tasks running
# (crash loops, failing health checks, can't pull the image, out of capacity).
resource "aws_cloudwatch_metric_alarm" "tasks_below_desired" {
  for_each = var.services

  alarm_name          = "${var.name}-${each.key}-tasks-below-desired"
  alarm_description   = "${each.key}: fewer tasks running than desired for 5 minutes"
  evaluation_periods  = 5
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic

  metric_query {
    id          = "missing"
    expression  = "desired - running"
    label       = "Tasks missing"
    return_data = true
  }

  metric_query {
    id = "desired"
    metric {
      namespace   = "ECS/ContainerInsights"
      metric_name = "DesiredTaskCount"
      dimensions  = { ClusterName = local.cluster, ServiceName = "${var.name}-${each.key}" }
      stat        = "Average"
      period      = 60
    }
  }

  metric_query {
    id = "running"
    metric {
      namespace   = "ECS/ContainerInsights"
      metric_name = "RunningTaskCount"
      dimensions  = { ClusterName = local.cluster, ServiceName = "${var.name}-${each.key}" }
      stat        = "Average"
      period      = 60
    }
  }
}

resource "aws_cloudwatch_metric_alarm" "service_cpu" {
  for_each = var.services

  alarm_name          = "${var.name}-${each.key}-cpu-high"
  alarm_description   = "${each.key}: CPU above 80% for 10 minutes"
  namespace           = "AWS/ECS"
  metric_name         = "CPUUtilization"
  dimensions          = { ClusterName = local.cluster, ServiceName = "${var.name}-${each.key}" }
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 2
  threshold           = 80
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

resource "aws_cloudwatch_metric_alarm" "service_memory" {
  for_each = var.services

  alarm_name          = "${var.name}-${each.key}-memory-high"
  alarm_description   = "${each.key}: memory above 80% for 10 minutes"
  namespace           = "AWS/ECS"
  metric_name         = "MemoryUtilization"
  dimensions          = { ClusterName = local.cluster, ServiceName = "${var.name}-${each.key}" }
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 2
  threshold           = 80
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

# ---------- Backend logs ----------

# app.py logs "Database unavailable: ..." whenever a request can't reach Postgres.
# This catches the failure the health check deliberately ignores (liveness != readiness).
resource "aws_cloudwatch_log_metric_filter" "db_unavailable" {
  name           = "${var.name}-db-unavailable"
  log_group_name = "/ecs/${var.name}-backend"
  pattern        = "\"Database unavailable\""

  metric_transformation {
    name          = "DatabaseUnavailable"
    namespace     = "MyECS/Backend"
    value         = "1"
    default_value = "0"
  }
}

resource "aws_cloudwatch_metric_alarm" "db_unavailable" {
  alarm_name          = "${var.name}-backend-db-unavailable"
  alarm_description   = "Backend requests are failing to reach the database (see /ecs/${var.name}-backend logs)"
  namespace           = "MyECS/Backend"
  metric_name         = "DatabaseUnavailable"
  statistic           = "Sum"
  period              = 60
  evaluation_periods  = 2
  datapoints_to_alarm = 1
  threshold           = 3
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

# ---------- RDS ----------

resource "aws_cloudwatch_metric_alarm" "rds_cpu" {
  alarm_name          = "${var.name}-rds-cpu-high"
  alarm_description   = "RDS CPU above 80% for 10 minutes"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  dimensions          = { DBInstanceIdentifier = local.db_instance }
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 2
  threshold           = 80
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

resource "aws_cloudwatch_metric_alarm" "rds_storage" {
  alarm_name          = "${var.name}-rds-storage-low"
  alarm_description   = "RDS free storage below 2 GiB (of 20)"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  dimensions          = { DBInstanceIdentifier = local.db_instance }
  statistic           = "Minimum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 2 * 1024 * 1024 * 1024
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}

# db.t4g.micro allows roughly 80 connections; warn well before that
resource "aws_cloudwatch_metric_alarm" "rds_connections" {
  alarm_name          = "${var.name}-rds-connections-high"
  alarm_description   = "RDS connections above 60 (db.t4g.micro limit is ~80)"
  namespace           = "AWS/RDS"
  metric_name         = "DatabaseConnections"
  dimensions          = { DBInstanceIdentifier = local.db_instance }
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 60
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_topic
  ok_actions          = local.alarm_topic
}
